### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by aleishio** [davidsantosmerino/filmaffinity-api#7]
How many request per minute can the API support?

**Comment by dsantosmerino** [comment]
Hey @aleixordeig! Thanks for opening the issue. It looks like Filmaffinity was returning a `429`. Now, after restarting the dyno and changing the IP it works again.

However, keep in mind that this a non-official API, that behind the scenes is making requests to the official website. I cannot say a specific number of requests that we can support, but of course, I suggest to don't abuse using it and don't use it for commercial projects since it could start failing at any moment.
