### ISSUE TITLE
Endpoint seems to be KO

### ISSUE THREAD

**Issue by smtdev** [davidsantosmerino/filmaffinity-api#8]
I'm trying to access to your published heroku [endpoint ](https://filmaffinity-unofficial.herokuapp.com/) but it seems to be down. Did you drop down the service?

Thanks!

**Comment by dsantosmerino** [comment]
Hey @smtdev, sorry for the late response.

It looks like is working as expected now. As I mentioned in similar issues, the problem is that we exhausted the free quota for the past month. The next **dyno type costs 7$/month**, I can consider an upgrade if required.

However, I'd like to know more about your **use case of this API and understand your requirements**. Also, I'd like to know if you and other developers around will be **interested in contributing a bit somehow to maintain a stable version**.

**Comment by smtdev** [comment]
Hey @dsantosmerino, thanks for your reply.

I just wanted to check how the API works. You did a great job! I won't use it, not yet at least, but I'll come back to you in case of yes :-).
